const $=id=>document.getElementById(id);
let setup=false,state=null;
const message=(text,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'';};
async function api(path,body){
  const response=await fetch(path,{credentials:'same-origin',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
  const result=await response.json();if(response.status===401){state=null;$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;}if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;
}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,action){const b=node('button',text);b.type='button';b.onclick=()=>guard(action);return b;}
async function guard(action){try{await action();}catch(error){message(error.message,true);}}
function showJson(id,result){$(id).hidden=false;$(id).textContent=JSON.stringify(result,null,2);}
function record(parent,title){const el=node('article',undefined,'record');el.append(node('strong',title));parent.append(el);return el;}
function bindForm(id,action){$(id).onsubmit=event=>{event.preventDefault();const submit=event.submitter;guard(async()=>{submit.disabled=true;try{await action(Object.fromEntries(new FormData($(id))));}finally{submit.disabled=false;}});};}
async function session(){const s=await api('/api/session');setup=s.setup_required;$('login').hidden=!!s.owner;$('workspace').hidden=!s.owner;$('logout').hidden=!s.owner;$('nameLabel').hidden=!setup;$('loginTitle').textContent=setup?'Set up your private workspace':'Sign in';if(s.owner)await refresh();}
async function refresh(){
  state=await api('/api/state');
  for(const id of ['portfolioList','inboxList','relationshipList','subscriptions','jobs'])$(id).replaceChildren();
  if(!state.portfolio.length)$('portfolioList').append(node('p','No saved policies yet.'));
  for(const row of state.portfolio){const el=record($('portfolioList'),`${row.account_id} · ${row.policy_id} · USDOT ${row.dot_number}`);el.append(node('p',`${row.policy_start} to ${row.policy_end} · ${row.status} · ${row.review_status}`));el.append(button('Edit policy',()=>{for(const field of $('portfolioForm').elements)if(field.name)field.value=row[field.name]??'';$('portfolioForm').scrollIntoView();}),button('Subscribe to evidence changes',async()=>{await api('/api/subscribe',{dot:row.dot_number,enabled:true});await refresh();message('Subscribed. The first verified check establishes a baseline.');}));}
  for(const sub of state.subscriptions){const el=record($('subscriptions'),`USDOT ${sub.dot} · ${sub.enabled?'Enabled':'Paused'}`);el.append(button(sub.enabled?'Pause':'Resume',async()=>{await api('/api/subscribe',{dot:sub.dot,enabled:!sub.enabled});await refresh();}));}
  $('schedule').textContent=state.schedule.next_run?`Next scheduled check: ${new Date(Number(state.schedule.next_run)*1000).toLocaleString()}. Service must remain running.`:'Enabled subscriptions are picked up within 30 seconds, then checked daily.';
  for(const job of state.jobs.slice(0,5)){const el=record($('jobs'),`Check ${job.id} · ${job.status}`);el.append(node('small',`${job.started_at} ${job.finished_at?'→ '+job.finished_at:''}`));if(job.detail){const details=node('details');details.append(node('summary','Check details'),node('pre',job.detail));el.append(details);}}
  if(!state.inbox.length)$('inboxList').append(node('p','No delivered alerts. This does not establish that a carrier has no risk.'));
  for(const item of state.inbox){const data=JSON.parse(item.payload),el=record($('inboxList'),`${item.read_at?'Read':'Unread'} · USDOT ${item.dot} · ${data.rule}`);el.append(node('p',data.materiality),node('small',`Observed ${data.previous_observed_at} → ${data.current_observed_at}; delivered ${item.delivered_at}`));const details=node('details');details.append(node('summary','Previous and current evidence'),node('pre',JSON.stringify(data,null,2)));el.append(details);if(!item.read_at)el.append(button('Mark read',async()=>{await api('/api/read',{id:item.alert_id});await refresh();}));}
  if(!state.relationships.length)$('relationshipList').append(node('p','No relationship proposals yet.'));
  for(const rel of state.relationships){const el=record($('relationshipList'),`${rel.dot_a} ↔ ${rel.dot_b} · ${rel.kind} · ${rel.status}`);el.append(node('p',rel.notes));const link=node('a','Review evidence');link.href=rel.evidence_url;link.target='_blank';link.rel='noopener noreferrer';el.append(link);if(rel.reviewer)el.append(node('p',`Reviewed by ${rel.reviewer}: ${rel.review_note}`));const note=node('textarea');note.placeholder='Record the rationale for your review decision';note.setAttribute('aria-label',`Review rationale for ${rel.dot_a} and ${rel.dot_b}`);el.append(note);for(const status of ['approved','rejected','revoked'])el.append(button(status,async()=>{await api('/api/review',{id:rel.id,status,review_note:note.value});await refresh();message('Review decision saved with history.');}));}
  $('forecast').textContent=`${state.forecast.status}: ${state.forecast.reasons.join('; ')}. No predictive score has been produced.`;
}
bindForm('loginForm',async data=>{await api(setup?'/api/setup':'/api/login',data);$('loginForm').reset();message('Signed in to the local workspace.');await session();});
$('logout').onclick=()=>guard(async()=>{await api('/api/logout',{});state=null;await session();message('Signed out.');});
bindForm('portfolioForm',async data=>{for(const key of ['scheduled_units','insured_vmt'])data[key]=data[key]===''?null:Number(data[key]);const prior=state.portfolio.find(r=>r.account_id===data.account_id&&r.policy_id===data.policy_id);await api('/api/portfolio',{records:[{...prior,...data}]});await refresh();message('Policy saved.');});
bindForm('subscriptionForm',async data=>{await api('/api/subscribe',{dot:data.dot,enabled:data.enabled==='true'});await refresh();message('Subscription saved.');});
bindForm('relationshipForm',async data=>{await api('/api/relationship',data);await refresh();message('Proposal saved. It will not enter a corporate group until reviewed and approved.');});
bindForm('groupForm',async data=>{message('Aggregating approved members and published safety records…');const r=await api('/api/group?'+new URLSearchParams(data));showJson('groupResult',r);$('groupSummary').replaceChildren();const el=record($('groupSummary'),`${r.members.length} group members · ${r.approved_relationships.length} approved ownership links · ${r.matched} Census matches`);el.append(node('p',r.limitation));if(!r.approved_relationships.length)el.append(node('p','No approved ownership links: this is a single-DOT view.'));for(const [field,v]of Object.entries(r.reported_totals))el.append(node('p',`${({power_units:'Reported power units',total_drivers:'Reported drivers',mcs150_mileage:'Reported mileage'})[field]}: ${v.sum===null?'Unavailable':v.sum.toLocaleString()} · ${v.known}/${v.denominator} members reported`));renderSafety(el,r.safety);dataTable(el,['USDOT','Carrier','Status','Report date','Inspections','Crash vehicle reports'],r.reports.map(row=>[row.dot,row.name??'Unavailable',row.status??'Unknown',row.report_date??'Unknown',number(r.safety.by_dot[row.dot].inspections.count),number(r.safety.by_dot[row.dot].crash_reports.count)]));if(r.missing.length)el.append(node('p',`Missing Census members: ${r.missing.join(', ')}`));message('Corporate aggregation complete. Review source windows and any missing evidence below.');});
bindForm('peerForm',async data=>{const result=await api('/api/peers?'+new URLSearchParams(data));showJson('peerResult',result);$('peerSummary').replaceChildren();const el=record($('peerSummary'),`${result.status} · ${result.eligible_count.toLocaleString()} eligible / ${result.candidate_count.toLocaleString()} candidates`);el.append(node('p',`${result.excluded_count.toLocaleString()} excluded. ${result.eligibility}`));if(result.quartiles){const table=node('table'),head=node('tr');for(const title of ['Reported exposure','This carrier','25th percentile','Median','75th percentile'])head.append(node('th',title));table.append(head);for(const [name,values]of Object.entries(result.quartiles)){const tr=node('tr');tr.append(node('td',name==='power_units'?'Power units':'Drivers'));tr.append(node('td',Number(result.target[name==='drivers'?'total_drivers':'power_units']).toLocaleString()));for(const value of values)tr.append(node('td',Number(value).toLocaleString()));table.append(tr);}const wrap=node('div',undefined,'table-wrap');wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Peer comparison table');wrap.tabIndex=0;wrap.append(table);el.append(wrap);}el.append(node('p',result.limitation));});
bindForm('recallForm',async data=>{message('Loading official NHTSA campaign candidates…');const result=await api('/api/recalls?'+new URLSearchParams(data));$('recallList').replaceChildren(node('p',`${result.results.length} campaign candidates · observed ${result.observed_at}. ${result.limitation}`));for(const r of result.results){const el=record($('recallList'),`${r.NHTSACampaignNumber??'Campaign'} · ${r.Component??''}`);el.append(node('p',r.Summary??''),node('p',`Remedy: ${r.Remedy??'Unavailable'}`));}message('Recall candidate lookup complete.');});
$('runNow').onclick=()=>guard(async()=>{const r=await api('/api/run',{});message(r.note);await refresh();});
$('historyButton').onclick=()=>guard(async()=>showJson('historyResult',await api('/api/history')));
$('importButton').onclick=()=>guard(async()=>{const file=$('importFile').files[0];if(!file||file.size>2_000_000)throw new Error('Select a JSON import of at most 2 MB');const envelope=JSON.parse(await file.text());if(envelope.schema!=='INSURER_PORTFOLIO_1')throw new Error('INSURER_PORTFOLIO_1 envelope required');const result=await api('/api/portfolio',{records:envelope.records});await refresh();message(`${result.changes} policies changed.`);});
$('exportButton').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'INSURER_PORTFOLIO_1',records:state.portfolio},null,2)],{type:'application/json'}));const link=node('a');link.href=url;link.download='private-portfolio.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function displayDate(value){if(!value)return 'unknown';const text=String(value);return /^\d{8}$/.test(text)?`${text.slice(0,4)}-${text.slice(4,6)}-${text.slice(6,8)}`:text.slice(0,10);}
function number(value){return value===null||value===undefined?'Unavailable':value.toLocaleString();}
function dataTable(parent,headers,rows){const table=node('table'),head=node('thead'),hr=node('tr');for(const label of headers)hr.append(node('th',label));head.append(hr);table.append(head);const body=node('tbody');for(const values of rows){const tr=node('tr');for(const value of values)tr.append(node('td',String(value??'Unknown')));body.append(tr);}table.append(body);const wrap=node('div',undefined,'table-wrap');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',headers.join(', '));wrap.append(table);parent.append(wrap);}
function sourceDetails(parent,result){const details=node('details');details.append(node('summary','Source records and calculation evidence'),node('pre',JSON.stringify(result,null,2)),button('Download evidence JSON',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const link=node('a');link.href=url;link.download='transport3r-identity-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));parent.append(details);}
function carrierLink(identifier){const link=node('a',`Open carrier ${identifier}`);link.href=`https://jeremyhennessy.github.io/Transport3r/#/carrier/${identifier}/summary`;link.target='_blank';link.rel='noopener noreferrer';return link;}
function renderSafety(parent,safety){parent.append(node('h3',`Published safety activity · ${safety.window.start} to ${safety.window.end}`));for(const [name,m]of Object.entries(safety.metrics)){const title=name==='inspections'?'Inspections':'Crash vehicle reports';parent.append(node('p',`${title}: ${number(m.count)} · ${number(m.known_window_rows)} identified rows in the window · latest ${m.latest_event_date??'not observed'}`));if(m.oos)parent.append(node('p',`Inspections with OOS: ${number(m.oos.positive)} · OOS totals known for ${m.oos.known}/${m.known_window_rows} rows · rate ${m.oos.rate_pct===null?'unavailable':m.oos.rate_pct+'%'}`));const issues=Object.entries(m.issues).filter(([,count])=>count);if(issues.length)parent.append(node('p',`Evidence issues: ${issues.map(([name,count])=>`${name}: ${count}`).join('; ')}`,'error'));if(m.examples.length){const details=node('details');details.append(node('summary',`${title}: up to 25 source examples`));for(const e of m.examples){const p=node('p',`${e.date} · USDOT ${e.dot} · `),link=node('a',e.event_id);link.href=e.source_url;link.target='_blank';link.rel='noopener noreferrer';p.append(link);details.append(p);}parent.append(details);}}parent.append(node('p',safety.limitation,'note'));}
function caseForm(parent,context){const form=node('form',undefined,'case-form'),label=node('label','Review state'),select=node('select');for(const [value,text]of [['in_review','In review'],['dismissed','Dismissed'],['escalated','Escalated for investigation']]){const o=node('option',text);o.value=value;select.append(o);}label.append(select);const rationale=node('label','Review rationale'),notes=node('textarea');notes.required=true;notes.minLength=10;notes.maxLength=8000;rationale.append(notes);const submit=node('button','Save review case');submit.type='submit';form.append(label,rationale,submit);form.onsubmit=event=>{event.preventDefault();guard(async()=>{submit.disabled=true;try{await api('/api/screening-case',{...context,status:select.value,notes:notes.value});await loadCases();message('Review saved with source evidence and an immutable decision history.');}finally{submit.disabled=false;}});};parent.append(form);}
let identityPage=1,identityDot='',ghostPage=1,ghostDays=365;
async function screenIdentity(identifier,page=1){$('identityResults').replaceChildren(node('p','Searching the verified nationwide registration publication…'));message('Checking shared registration evidence…');identityDot=identifier;identityPage=page;const r=await api('/api/identity-screen?'+new URLSearchParams({dot:identifier,page}));const target=$('identityResults');target.replaceChildren(node('h3',`${r.name} · USDOT ${r.dot}`),node('p',`${r.total.toLocaleString()} candidate registrations · page ${r.page} · status ${r.registration_status??'unknown'} · registered ${displayDate(r.added_date)} · source observed ${displayDate(r.source.available_at)}`),node('p',r.limitation,'note'));if(!r.candidates.length)target.append(node('p','No matches under these rules. This is not proof of no affiliation or identity misuse.'));for(const candidate of r.candidates){const el=record(target,`${candidate.name} · USDOT ${candidate.dot}`);el.append(node('p',`${candidate.review_reason.replaceAll('_',' ')} · ${candidate.category_count} ${candidate.category_count===1?'category':'categories'} · status ${candidate.registration_status??'unknown'} · registered ${displayDate(candidate.added_date)}`));dataTable(el,['Shared category','Normalized value','Matching registrations','Context'],candidate.matches.map(m=>[m.category.replaceAll('_',' '),m.value,m.matching_registration_count,m.common_detail?'Common detail: shared-service explanation needs review':'Review the exact source evidence']));el.append(carrierLink(candidate.dot),button('Draft shared-details relationship',()=>{const form=$('relationshipForm');form.elements.dot_a.value=r.dot;form.elements.dot_b.value=candidate.dot;form.elements.kind.value='shared_registration_details';form.elements.evidence_url.value=r.source.url;form.elements.notes.value=`Shared registration lead, ${r.ruleset}, source observed ${r.source.available_at}. Categories: ${candidate.matches.map(m=>m.category).join(', ')}. Ownership and evasion not established.`;form.scrollIntoView();message('Draft prepared. Review the evidence before saving; this does not add corporate membership.');}));caseForm(el,{kind:'chameleon',dot:r.dot,candidate_dot:candidate.dot,page:r.page});}const previous=button('Previous candidates',()=>screenIdentity(identityDot,identityPage-1)),next=button('Next candidates',()=>screenIdentity(identityDot,identityPage+1));previous.disabled=page===1;next.disabled=!r.has_next;target.append(previous,next);sourceDetails(target,r);message('Shared-registration screening complete. Findings require review.');}
bindForm('identityForm',data=>screenIdentity(data.dot));
async function reviewGhost(identifier,days=365){$('ghostResult').replaceChildren(node('p','Checking registration and dated source activity…'));const r=await api('/api/ghost?'+new URLSearchParams({dot:identifier,days}));const el=$('ghostResult');el.replaceChildren(node('h3',`${r.name??'Registration unresolved'} · USDOT ${r.dot}`),node('p',`${r.finding.replaceAll('_',' ')} · Census status ${r.registration_status??'unknown'}`),node('p',r.limitation,'note'));el.append(node('p','Activity while inactive: not established. Status effective date is unavailable.'),carrierLink(r.dot));renderSafety(el,r.activity);caseForm(el,{kind:'ghost',dot:r.dot,days});sourceDetails(el,r);message('Registration/activity review complete.');}
bindForm('ghostForm',data=>reviewGhost(data.dot,Number(data.days)));
async function loadGhostQueue(page=1){$('ghostQueue').replaceChildren(node('p','Searching nationwide registrations and published activity…'));const r=await api('/api/ghost-queue?'+new URLSearchParams({days:ghostDays,page}));ghostPage=page;const el=$('ghostQueue');el.replaceChildren(node('h3',`${r.total.toLocaleString()} status/activity candidates · page ${page}`),node('p',`${r.window.start} to ${r.window.end}. ${r.limitation}`,'note'));for(const row of r.rows){const entry=record(el,`${row.name} · USDOT ${row.dot}`);entry.append(node('p',`Status ${row.registration_status} · latest activity ${row.latest_event_date}`),button('Review activity evidence',async()=>{await reviewGhost(row.dot,ghostDays);$('ghostResult').scrollIntoView();}));}const previous=button('Previous activity candidates',()=>loadGhostQueue(ghostPage-1)),next=button('Next activity candidates',()=>loadGhostQueue(ghostPage+1));previous.disabled=page===1;next.disabled=!r.has_next;el.append(previous,next);sourceDetails(el,{...r,rows:undefined});message('Nationwide status/activity queue loaded.');}
bindForm('ghostQueueForm',async data=>{ghostDays=Number(data.days);await loadGhostQueue();});
async function loadCases(){const r=await api('/api/state');const el=$('screeningCases');el.replaceChildren();if(!r.screening_cases.length)el.append(node('p','No saved identity review cases.'));for(const item of r.screening_cases){const entry=record(el,`${item.kind==='ghost'?'Status/activity':'Shared-registration'} · USDOT ${item.dot}${item.candidate_dot?' ↔ '+item.candidate_dot:''} · ${item.status}`);entry.append(node('p',item.notes),node('small',`${item.reviewer} · ${item.updated_at}`),button('View case evidence and history',async()=>{const evidence=await api('/api/screening-history?'+new URLSearchParams({id:item.id}));sourceDetails(entry,evidence);}),button('Recheck and update review',async()=>{if(item.kind==='ghost'){await reviewGhost(item.dot);$('ghostResult').scrollIntoView();}else{await screenIdentity(item.dot);$('identityResults').scrollIntoView();}}));}}
$('loadCases').onclick=()=>guard(loadCases);
guard(session);
// Refresh status without replacing unsaved forms or review rationales.
setInterval(()=>{if(state&&!document.querySelector('#relationshipList textarea:focus')&&!Array.from(document.querySelectorAll('#relationshipList textarea')).some(el=>el.value))guard(refresh);},30000);
