const $=id=>document.getElementById(id);
let setup=false,state=null;
const message=(text,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'';};
async function api(path,body){
  const response=await fetch(path,{credentials:'same-origin',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
  const result=await response.json();if(response.status===401){state=null;$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;}if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;
}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,action){const b=node('button',text);b.type='button';b.onclick=()=>guard(action);return b;}
async function guard(action){try{await action();}catch(error){message(error.message,true);}}
function showJson(id,result){$(id).hidden=false;$(id).textContent=JSON.stringify(result,null,2);}
function record(parent,title){const el=node('article',undefined,'record');el.append(node('strong',title));parent.append(el);return el;}
function bindForm(id,action){$(id).onsubmit=event=>{event.preventDefault();const submit=event.submitter;guard(async()=>{submit.disabled=true;try{await action(Object.fromEntries(new FormData($(id))));}finally{submit.disabled=false;}});};}
async function session(){const s=await api('/api/session');setup=s.setup_required;$('login').hidden=!!s.owner;$('workspace').hidden=!s.owner;$('logout').hidden=!s.owner;$('nameLabel').hidden=!setup;$('loginTitle').textContent=setup?'Set up your private workspace':'Sign in';if(s.owner)await refresh();}
async function refresh(){
  state=await api('/api/state');
  for(const id of ['portfolioList','inboxList','relationshipList','subscriptions','jobs'])$(id).replaceChildren();
  if(!state.portfolio.length)$('portfolioList').append(node('p','No saved policies yet.'));
  for(const row of state.portfolio){const el=record($('portfolioList'),`${row.account_id} · ${row.policy_id} · USDOT ${row.dot_number}`);el.append(node('p',`${row.policy_start} to ${row.policy_end} · ${row.status} · ${row.review_status}`));el.append(button('Edit policy',()=>{for(const field of $('portfolioForm').elements)if(field.name)field.value=row[field.name]??'';$('portfolioForm').scrollIntoView();}),button('Subscribe to evidence changes',async()=>{await api('/api/subscribe',{dot:row.dot_number,enabled:true});await refresh();message('Subscribed. The first verified check establishes a baseline.');}));}
  for(const sub of state.subscriptions){const el=record($('subscriptions'),`USDOT ${sub.dot} · ${sub.enabled?'Enabled':'Paused'}`);el.append(button(sub.enabled?'Pause':'Resume',async()=>{await api('/api/subscribe',{dot:sub.dot,enabled:!sub.enabled});await refresh();}));}
  $('schedule').textContent=state.schedule.next_run?`Next scheduled check: ${new Date(Number(state.schedule.next_run)*1000).toLocaleString()}. Service must remain running.`:'Enabled subscriptions are picked up within 30 seconds, then checked daily.';
  for(const job of state.jobs.slice(0,5)){const el=record($('jobs'),`Check ${job.id} · ${job.status}`);el.append(node('small',`${job.started_at} ${job.finished_at?'→ '+job.finished_at:''}`));if(job.detail){const details=node('details');details.append(node('summary','Check details'),node('pre',job.detail));el.append(details);}}
  if(!state.inbox.length)$('inboxList').append(node('p','No delivered alerts. This does not establish that a carrier has no risk.'));
  for(const item of state.inbox){const data=JSON.parse(item.payload),el=record($('inboxList'),`${item.read_at?'Read':'Unread'} · USDOT ${item.dot} · ${data.rule}`);el.append(node('p',data.materiality),node('small',`Observed ${data.previous_observed_at} → ${data.current_observed_at}; delivered ${item.delivered_at}`));const details=node('details');details.append(node('summary','Previous and current evidence'),node('pre',JSON.stringify(data,null,2)));el.append(details);if(!item.read_at)el.append(button('Mark read',async()=>{await api('/api/read',{id:item.alert_id});await refresh();}));}
  if(!state.relationships.length)$('relationshipList').append(node('p','No relationship proposals yet.'));
  for(const rel of state.relationships){const el=record($('relationshipList'),`${rel.dot_a} ↔ ${rel.dot_b} · ${rel.kind} · ${rel.status}`);el.append(node('p',rel.notes));const link=node('a','Review evidence');link.href=rel.evidence_url;link.target='_blank';link.rel='noopener noreferrer';el.append(link);if(rel.reviewer)el.append(node('p',`Reviewed by ${rel.reviewer}: ${rel.review_note}`));const note=node('textarea');note.placeholder='Record the rationale for your review decision';note.setAttribute('aria-label',`Review rationale for ${rel.dot_a} and ${rel.dot_b}`);el.append(note);for(const status of ['approved','rejected','revoked'])el.append(button(status,async()=>{await api('/api/review',{id:rel.id,status,review_note:note.value});await refresh();message('Review decision saved with history.');}));}
  $('forecast').textContent=`${state.forecast.status}: ${state.forecast.reasons.join('; ')}. No predictive score has been produced.`;
}
bindForm('loginForm',async data=>{await api(setup?'/api/setup':'/api/login',data);$('loginForm').reset();message('Signed in to the local workspace.');await session();});
$('logout').onclick=()=>guard(async()=>{await api('/api/logout',{});state=null;await session();message('Signed out.');});
bindForm('portfolioForm',async data=>{for(const key of ['scheduled_units','insured_vmt'])data[key]=data[key]===''?null:Number(data[key]);const prior=state.portfolio.find(r=>r.account_id===data.account_id&&r.policy_id===data.policy_id);await api('/api/portfolio',{records:[{...prior,...data}]});await refresh();message('Policy saved.');});
bindForm('subscriptionForm',async data=>{await api('/api/subscribe',{dot:data.dot,enabled:data.enabled==='true'});await refresh();message('Subscription saved.');});
bindForm('relationshipForm',async data=>{await api('/api/relationship',data);await refresh();message('Proposal saved. It will not enter a corporate group until reviewed and approved.');});
bindForm('groupForm',async data=>{const r=await api('/api/group?'+new URLSearchParams(data));showJson('groupResult',r);$('groupSummary').replaceChildren();const el=record($('groupSummary'),`${r.members.length} reviewed group members · ${r.matched} Census matches`);el.append(node('p',r.limitation));for(const [field,v]of Object.entries(r.reported_totals))el.append(node('p',`${({power_units:'Reported power units',total_drivers:'Reported drivers',mcs150_mileage:'Reported mileage'})[field]}: ${v.sum===null?'Unavailable':v.sum.toLocaleString()} · ${v.known}/${v.denominator} members reported`));for(const row of r.reports)el.append(node('p',`USDOT ${row.dot} · ${row.name??'Name unavailable'} · status ${row.status??'unknown'} · MCS-150 ${row.report_date??'unknown'} · mileage year ${row.mileage_year??'unknown'}`));});
bindForm('peerForm',async data=>{const result=await api('/api/peers?'+new URLSearchParams(data));showJson('peerResult',result);$('peerSummary').replaceChildren();const el=record($('peerSummary'),`${result.status} · ${result.eligible_count.toLocaleString()} eligible / ${result.candidate_count.toLocaleString()} candidates`);el.append(node('p',`${result.excluded_count.toLocaleString()} excluded. ${result.eligibility}`));if(result.quartiles){const table=node('table'),head=node('tr');for(const title of ['Reported exposure','This carrier','25th percentile','Median','75th percentile'])head.append(node('th',title));table.append(head);for(const [name,values]of Object.entries(result.quartiles)){const tr=node('tr');tr.append(node('td',name==='power_units'?'Power units':'Drivers'));tr.append(node('td',Number(result.target[name==='drivers'?'total_drivers':'power_units']).toLocaleString()));for(const value of values)tr.append(node('td',Number(value).toLocaleString()));table.append(tr);}el.append(table);}el.append(node('p',result.limitation));});
bindForm('recallForm',async data=>{message('Loading official NHTSA campaign candidates…');const result=await api('/api/recalls?'+new URLSearchParams(data));$('recallList').replaceChildren(node('p',`${result.results.length} campaign candidates · observed ${result.observed_at}. ${result.limitation}`));for(const r of result.results){const el=record($('recallList'),`${r.NHTSACampaignNumber??'Campaign'} · ${r.Component??''}`);el.append(node('p',r.Summary??''),node('p',`Remedy: ${r.Remedy??'Unavailable'}`));}message('Recall candidate lookup complete.');});
$('runNow').onclick=()=>guard(async()=>{const r=await api('/api/run',{});message(r.note);await refresh();});
$('historyButton').onclick=()=>guard(async()=>showJson('historyResult',await api('/api/history')));
$('importButton').onclick=()=>guard(async()=>{const file=$('importFile').files[0];if(!file||file.size>2_000_000)throw new Error('Select a JSON import of at most 2 MB');const envelope=JSON.parse(await file.text());if(envelope.schema!=='INSURER_PORTFOLIO_1')throw new Error('INSURER_PORTFOLIO_1 envelope required');const result=await api('/api/portfolio',{records:envelope.records});await refresh();message(`${result.changes} policies changed.`);});
$('exportButton').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'INSURER_PORTFOLIO_1',records:state.portfolio},null,2)],{type:'application/json'}));const link=node('a');link.href=url;link.download='private-portfolio.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
guard(session);
// Refresh status without replacing unsaved forms or review rationales.
setInterval(()=>{if(state&&!document.querySelector('#relationshipList textarea:focus')&&!Array.from(document.querySelectorAll('#relationshipList textarea')).some(el=>el.value))guard(refresh);},30000);
