import {useEffect,useState} from 'react';
import {type CarrierEvidence,type EvidenceKey,SOURCE_IDS} from './carrierEvidence';
import {loadSafetyWindow,type SafetyWindowResult,windowMonths} from './safetyWindow';
import {validateEventWindow} from './eventWindow';
import {reportModel,appendixColumns,reportArchive} from './reportModel';
import {readValue} from './datahub';
import {Bars,Timeline} from './CarrierInsight';
import {SafetyVisuals} from './SafetyVisuals';
import {replayCarrierInspectionMeasures} from './smsReplay';
import './report.css';
import {completeCarrier,type CompleteProgress} from './completeEvidence';

function ReportPages({evidence,window,detailed,volume}:{evidence:CarrierEvidence;window:SafetyWindowResult;detailed:boolean;volume:number}) {
  const model=reportModel(evidence,window);
  const totalRows=Object.entries(evidence.slices).reduce((n,[k,s])=>n+(k==='census'?0:s?.rows.length??0),0),volumeSize=totalRows>2000?1000:Infinity;let rowOffset=0;
  const heading=(title:string)=><header><div className="report-brand">Transport<span>3r</span></div><div><strong>{model.name}</strong><small>USDOT {model.dot} · {title}</small></div></header>;
  const scope=<p className="report-scope">Daily event window: {model.window.start} through {model.window.end}. Generated {model.generatedAt}. Census report and SMS release dates are separate; an exact shared SMS month is not established.</p>;
  return <article className="carrier-report" data-testid="carrier-report" data-dot={model.dot}>
    <style>{`@page { @bottom-center { content: "Transport3r | USDOT ${model.dot} | Page " counter(page) " of " counter(pages); font: 8pt Arial; color: #52657b; } }`}</style>
    <section className="report-page">{heading('Carrier Brief · Identity and exposure')}<h1>{model.name}</h1>{model.dba&&<p>DBA {model.dba}</p>}<p>{model.address}</p>{scope}<h2>Executive summary</h2>{model.view.paragraphs.slice(0,3).map(text=><p key={text}>{text}</p>)}<div className="report-metrics">{model.metrics.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><h2>Evidence to resolve</h2><p>{model.view.limitation}</p><p>{model.view.gaps.slice(0,8).map(row=>`${row.key}: ${row.status}`).join('; ')||'No partial or unavailable requests in this acquisition. Request completeness does not establish complete history.'}{model.view.gaps.length>8?`; and ${model.view.gaps.length-8} more - see evidence appendix.`:''}</p><p className="report-note">FMCSA public evidence is a review aid. Crash involvement does not establish fault. No Transport3r risk score or insurance-loss probability is released.</p></section>
    <section className="report-page">{heading('Carrier Brief · Daily safety activity')}{scope}<div className="report-charts">{window.sources.map(source=>source.slice&&!source.error?<Bars key={source.id} title={source.label} rows={windowMonths(source.slice).map(month=>({label:month.month,count:month.loaded}))} note={source.slice.truncated?'Loaded lower bounds; selected source total may exceed plotted records.':'Returned daily records in the selected window.'}/>:<p key={source.id}>{source.label}: unavailable. {source.error}</p>)}</div><SafetyVisuals result={window} print/><p className="report-note">Map symbols represent state clusters, not exact event sites. Inspection reporting jurisdiction is a fallback, explicitly distinguished from location state. No coordinates were geocoded.</p></section>
    <section className="report-page">{heading('Carrier Brief · Site visit preparation')}<h2>What to verify on site</h2><ul>{model.checklist.map(text=><li key={text}>{text}</li>)}</ul><h2>Authority and insurance context</h2>{model.view.paragraphs.slice(3,5).map(text=><p key={text}>{text}</p>)}<h2>Official SMS context</h2><p>{model.view.paragraphs[5]}</p>{model.sms.status==='available'&&<table><thead><tr><th>BASIC</th><th>Official measure</th><th>Published percentile</th></tr></thead><tbody>{model.sms.basics.map(basic=><tr key={basic.key}><td>{basic.label}</td><td>{basic.measure??'Not reported'}</td><td>{model.sms.passenger?basic.percentile??'Not reported':'Not public in general output'}</td></tr>)}</tbody></table>}<h2>Sources and limitations</h2><p className="report-note">Company Census az4n-8mr2; daily inspections fx4q-ay7w; daily crashes aayw-vxb3; MOTUS authority inys-ebih; insurance c5y8-a4uz. Official source pages: data.transportation.gov/d/SOURCE-ID. Registry metadata captured {evidence.registry.generated_at??'unknown'}. Live window acquisition {window.acquiredAt}; {window.sources.map(source=>`${source.id} publication ${source.after?.rowsUpdatedAt?new Date(source.after.rowsUpdatedAt*1000).toISOString():'unavailable'}`).join('; ')}. Download the evidence archive for all retained records, fields and acquisition details. Any unavailable source is listed explicitly.</p></section>
    {detailed&&<div className="report-appendix" data-testid="report-appendix">{heading('Detailed evidence appendix')}<h1>Evidence appendix</h1>{scope}<h2>Identity and reported exposure</h2><table><tbody>{Object.entries(evidence.census??evidence.slices.census?.rows[0]??{}).map(([key,val])=><tr key={key}><th>{key}</th><td>{String(val??'Not reported')}</td></tr>)}</tbody></table><h2>Source coverage</h2><table><thead><tr><th>Source / family</th><th>State</th><th>Loaded / total</th><th>Acquired / event range</th></tr></thead><tbody>{model.coverage.map(row=><tr key={row.key}><td>{row.key}<br/>{row.sourceId}</td><td>{row.status}</td><td>{row.loaded??'Unknown'} / {row.requestTotal??'Unknown'}</td><td>{row.acquiredAt??'Unavailable'}<br/>{row.range?.start??'No event range'} - {row.range?.end??''}</td></tr>)}</tbody></table>
      <Timeline evidence={evidence} keys={['motusAuthHistory','motusRevokeSuspend','motusInsuranceHistory','newEntrantOos']}/>
      <h2>Transport calculated SMS replay</h2><p>Separate from official measures. Unknown denominator/input populations suppress unavailable calculations. No TRI.</p><table><thead><tr><th>BASIC</th><th>Official</th><th>Calculated</th><th>Status</th></tr></thead><tbody>{replayCarrierInspectionMeasures(evidence).map(row=><tr key={row.basic}><td>{row.label}</td><td>{row.officialMeasure??'Unavailable'}</td><td>{row.calculatedMeasure??'Unavailable'}</td><td>{row.status}</td></tr>)}</tbody></table>
      {(Object.keys(SOURCE_IDS) as EvidenceKey[]).filter(key=>key!=='census').map(key=>{const slice=evidence.slices[key],rows=evidence.errors[key]?[]:slice?.rows??[],columns=appendixColumns(key,rows),offset=rowOffset;rowOffset+=rows.length;const visible=rows.slice(Math.max(0,volumeSize===Infinity?0:(volume-1)*volumeSize-offset),Math.max(0,volume*volumeSize-offset));return <section key={key} className="report-source"><h2>{key} · {SOURCE_IDS[key]}</h2><p>{evidence.errors[key]??(!slice?'Unavailable':`${rows.length} loaded rows${slice.truncated?' - partial source/parent window':''}; acquired ${slice.acquiredAt??'unknown'}.`)} {totalRows>2000?`Appendix volume ${volume}; ${visible.length} rows shown from this source. Select other volumes to print all records.`:null} Key fields are shown; the evidence archive retains every returned row and field. No monetary unit conversion is applied.</p>{rows.length>0?<table><thead><tr><th>#</th>{columns.map(field=><th key={field}>{field.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{visible.map((row,index)=><tr key={index}><td>{rows.indexOf(row)+1}</td>{columns.map(field=><td key={field}>{readValue(row,[field])??'Not reported'}</td>)}</tr>)}</tbody></table>:<p>{slice&&!evidence.errors[key]?'No rows returned in this scope.':'No usable records.'} Missing evidence is not zero risk.</p>}</section>;})}</div>}
    <footer className="report-footer">Transport3r · USDOT {model.dot} · Generated {model.generatedAt.slice(0,10)} · Public evidence / review required</footer>
  </article>;
}
export default function CarrierReport() {
  const dot=location.hash.split('/')[2],params=new URLSearchParams(location.hash.split('?')[1]??''),today=new Date().toISOString().slice(0,10);
  const detailed=params.get('format')==='detailed';
  const [start,setStart]=useState(params.get('start')??`${today.slice(0,4)}-01-01`),[end,setEnd]=useState(params.get('end')??today),[version,setVersion]=useState(0),[volume,setVolume]=useState(1),[progress,setProgress]=useState<CompleteProgress|null>(null);
  const [result,setResult]=useState<{evidence:CarrierEvidence;window:SafetyWindowResult}|null>(null),[error,setError]=useState('');
  useEffect(()=>{let current=true;setResult(null);setError('');void (async()=>{const selected=validateEventWindow({start,end});const task=completeCarrier(dot,p=>current&&setProgress(p));let evidence:CarrierEvidence;try{evidence=await task.promise;}finally{task.unsubscribe();}const window=await loadSafetyWindow(evidence.registry,dot,selected,true);reportModel(evidence,window);if(current)setResult({evidence,window});})().catch(cause=>{if(current)setError(String(cause));});return()=>{current=false;};},[dot,version]);
  const totalRows=result?Object.entries(result.evidence.slices).reduce((n,[k,s])=>n+(k==='census'?0:s?.rows.length??0),0):0;
  const exportJson=()=>{if(!result)return;const blob=new Blob([JSON.stringify(reportArchive(result.evidence,result.window),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`transport3r-${dot}-evidence.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <main className="report-screen"><div className="report-controls"><a href={`#/carrier/${dot}/summary`}>Back to carrier</a><h1>{detailed?'Detailed Carrier Report':'Carrier Brief'}</h1><p>Review this report, then choose Save as PDF in the print dialog. The brief is three designed pages; the detailed version includes source coverage and evidence rows. Large appendices use numbered volumes of 1,000 rows; the evidence archive includes every loaded record in one download. Paper size: A4, default scale.</p><form onSubmit={event=>{event.preventDefault();setVersion(v=>v+1);}}><label>Start date <input type="date" required value={start} onChange={event=>setStart(event.target.value)}/></label><label>End date <input type="date" required value={end} onChange={event=>setEnd(event.target.value)}/></label><button>Apply report window</button></form>{detailed&&totalRows>2000&&<label>Appendix volume <input type="number" min={1} max={Math.ceil(totalRows/1000)} value={volume} onChange={event=>setVolume(Math.max(1,Math.min(Math.ceil(totalRows/1000),Number(event.target.value)||1)))}/> of {Math.ceil(totalRows/1000)}</label>}<button disabled={!result} onClick={()=>window.print()}>{detailed?'Export Detailed Report':'Export Carrier Brief'} / Save PDF</button><button disabled={!result} onClick={exportJson}>Download evidence archive</button>{error&&<p role="alert">{error}</p>}{!result&&!error&&<p role="status">Preparing complete carrier evidence and selected daily window… {progress?.finished??0}/36 sources; {(progress?.rows??0).toLocaleString()} rows.</p>}</div>{result&&<ReportPages evidence={result.evidence} window={result.window} detailed={detailed} volume={volume}/>}</main>;
}
