import {useEffect,useRef,useState} from 'react';
import {completeCarrier,retryCompleteCarrier,type CompleteProgress} from './completeEvidence';
import {SOURCE_IDS,type CarrierEvidence,type CarrierEvidenceMode,type EvidenceKey} from './carrierEvidence';

export function mergeComplete(preview:CarrierEvidence|null,full:CarrierEvidence,mode:CarrierEvidenceMode):CarrierEvidence{
 const slices={...(preview?.dotNumber===full.dotNumber?preview.slices:{}),...full.slices},errors={...(preview?.dotNumber===full.dotNumber?preview.errors:{})};
 for(const key of Object.keys(full.slices) as EvidenceKey[])delete errors[key];
 for(const key of Object.keys(full.errors) as EvidenceKey[]){if(slices[key])slices[key]={...slices[key]!,truncated:true};else errors[key]=full.errors[key];}
 return {...full,mode,slices,errors,completeAttempted:true};
}
export function CompleteLoadStatus({dot,mode,onLoaded}:{dot:string;mode:CarrierEvidenceMode;onLoaded:(value:CarrierEvidence)=>void}){
 const [progress,setProgress]=useState<CompleteProgress|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const callback=useRef(onLoaded);callback.current=onLoaded;
 useEffect(()=>{let live=true;setProgress(null);setError('');const task=completeCarrier(dot,p=>live&&setProgress(p));task.promise.then(value=>{if(live){callback.current(value);if(Object.keys(value.errors).length)setError(Object.entries(value.errors).map(([key,message])=>`${key}: ${message}`).join('; '));}}).catch(cause=>live&&setError(String(cause)));return()=>{live=false;task.unsubscribe();};},[dot,mode,retry]);
 return <section className="c360-card" data-testid="complete-data-status"><h2>{progress?.status==='complete'?'Complete carrier evidence loaded':error?'Complete loading needs attention':'Loading complete carrier evidence'}</h2><p role="status">{progress?.finished??0} of 36 sources checked · {(progress?.rows??0).toLocaleString()} rows loaded. {progress?.status==='complete'?'All published records for this carrier were paged and source counts verified.':'The preview remains available while full source requests are checked.'}</p>{progress?.status==='loading'&&<progress max={36} value={progress.finished} aria-label="Complete source loading"/>}{error&&<p role="alert">Complete loading needs attention. {error}</p>}<button onClick={()=>{retryCompleteCarrier(dot);setRetry(n=>n+1);}}>Reload complete data</button><p>Completeness applies to current published files. It does not establish a full lifetime history or a shared SMS month.</p></section>;
}
export function AllSourceRecords({evidence}:{evidence:CarrierEvidence}){
 const [key,setKey]=useState<EvidenceKey>('inspections'),[page,setPage]=useState(1);
 const slice=evidence.slices[key],rows=evidence.errors[key]?[]:slice?.rows??[],pages=Math.max(1,Math.ceil(rows.length/50)),selected=Math.min(page,pages);
 const source=evidence.registry.sources.find(s=>s.id===SOURCE_IDS[key]);
 const exportAll=()=>{const blob=new Blob([JSON.stringify(evidence)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`transport3r-${evidence.dotNumber}-complete-evidence.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const exportRows=()=>{const blob=new Blob([JSON.stringify({dotNumber:evidence.dotNumber,source:SOURCE_IDS[key],acquiredAt:slice?.acquiredAt,complete:!!slice&&!slice.truncated,error:evidence.errors[key]??null,rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`transport3r-${evidence.dotNumber}-${SOURCE_IDS[key]}-all-records.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="c360-card" data-testid="all-source-records"><h2>Browse all source records</h2><button onClick={exportAll}>Download all loaded carrier evidence</button><label>Source <select value={key} onChange={event=>{setKey(event.target.value as EvidenceKey);setPage(1);}}>{(Object.keys(SOURCE_IDS) as EvidenceKey[]).map(k=><option key={k} value={k}>{evidence.registry.sources.find(s=>s.id===SOURCE_IDS[k])?.name??k} ({evidence.slices[k]?.rows.length??'?'})</option>)}</select></label><p>{source?.name??key} · {rows.length.toLocaleString()} loaded{slice?.truncated?' · partial; complete loading is pending or needs attention':''}. Every returned field is available within each record.</p>{evidence.errors[key]&&<p role="alert">{evidence.errors[key]}</p>}<div><button disabled={selected<=1} onClick={()=>setPage(selected-1)}>Previous records</button><label> Page <input type="number" min={1} max={pages} value={selected} onChange={event=>setPage(Math.max(1,Math.min(pages,Number(event.target.value)||1)))}/></label> of {pages} <button disabled={selected>=pages} onClick={()=>setPage(selected+1)}>Next records</button> <button disabled={!slice||!!evidence.errors[key]} onClick={exportRows}>Export all source records</button></div>{rows.slice((selected-1)*50,selected*50).map((row,index)=><details key={`${key}:${selected}:${index}`}><summary>Record {(selected-1)*50+index+1} · {String(row.inspection_id??row.unique_id??row.docket_number??row.prefix_docket_number??row.crash_id??row.dot_number??row.usdot_number??'Source record')}</summary><dl>{Object.entries(row).map(([field,value])=><div key={field}><dt><strong>{source?.columns.find(c=>c.field_name===field)?.name??field}</strong></dt><dd>{value===null||value===undefined?'Not reported':typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl></details>)}</section>;
}
