const sources = [
  {name:'US Census state boundaries',status:'Available on Safety maps and reports',url:'https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html',use:'Bundled 2025 state polygons for the inspection/crash regional display.',limit:'State symbols are regional display locations, not event coordinates. No carrier geocoding or operating-route inference.'},
  {name:'NHTSA vPIC vehicle specifications',status:'Available on VIN pages',url:'https://vpic.nhtsa.dot.gov/api/',use:'Make, model, model year, body class, weight class and fuel from an observed VIN.',limit:'A verified carrier inspection must contain the VIN. Decoder warnings remain visible; specifications do not prove ownership or current condition.'},
  {name:'NHTSA recall campaigns',status:'Research candidate',url:'https://www.nhtsa.gov/nhtsa-datasets-and-apis',use:'Model-year, make and model campaign context following a verified VIN decode.',limit:'Campaign matches do not establish that a specific VIN is affected or that a repair remains open. Manufacturer model names need reconciliation.'},
  {name:'PHMSA hazardous materials registration',status:'Join validation needed',url:'https://www.phmsa.dot.gov/registration/registration-information',use:'Hazmat registration history and covered registration periods.',limit:'Validate the downloadable identifiers and exact USDOT linkage before import. Registration alone does not establish carrier compliance.'},
  {name:'PHMSA hazardous materials incidents',status:'Join and grain validation needed',url:'https://www.phmsa.dot.gov/hazmat-program-management-data-and-statistics/data-operations/incident-statistics',use:'Reported release, commodity, event location and incident consequence context.',limit:'An incident can have multiple detail rows. Reporter names are discovery leads until carrier identity is independently matched.'},
  {name:'EPA SmartWay partners and performance',status:'Identity validation needed',url:'https://www.epa.gov/smartway/smartway-partner-list',use:'Voluntary sustainability participation and divisional-fleet performance context.',limit:'Match the correct company, division and data year. Participation and emissions indicators are separate from safety risk.'},
  {name:'BTS National Transportation Atlas Database',status:'Geographic context candidate',url:'https://www.bts.gov/ntad',use:'Freight networks, terminals and transportation infrastructure for future maps.',limit:'Infrastructure proximity to an address does not establish a carrier’s routes or operating exposure.'},
];
export function EnrichmentSources() {
  return <section className="t3-panel t3-window-panel" data-testid="enrichment-sources"><h2>Additional data sources</h2><p>Reviewed September 9, 2026. These sources are separate from the 36 configured FMCSA/DOT datasets. NHTSA VIN specifications and Census map boundaries are integrated; candidates below do not contribute carrier facts or scores.</p><div className="t3-enrichment-grid">{sources.map(source=><article key={source.name}><h3><a href={source.url} target="_blank" rel="noreferrer">{source.name} ↗</a></h3><strong>{source.status}</strong><p>{source.use}</p><p>{source.limit}</p></article>)}</div></section>;
}
