import {useState} from 'react';
import type {SafetyWindowResult} from './safetyWindow';
import {windowMonths} from './safetyWindow';
import {Bars} from './CarrierInsight';
import {eventGeography} from './eventGeography';
import boundaries from './stateBoundaries.json';
export function SafetyVisuals({result,print=false}:{result:SafetyWindowResult;print?:boolean}) {
  const [inspections,setInspections]=useState(true),[crashes,setCrashes]=useState(true),[selected,setSelected]=useState<string|null>(null);
  const geo=eventGeography(result),events=geo.events.filter(event=>(print||inspections||event.kind!=='inspection')&&(print||crashes||event.kind!=='crash'));
  const states=boundaries.states.map(state=>({...state,events:events.filter(event=>event.state===state.code)}));
  const selectedEvents=events.filter(event=>event.state===selected);
  return <section className="t3-safety-visuals" data-testid="safety-map"><h3>Daily event geography and activity</h3><p>{result.window.start} through {result.window.end} · USDOT {result.dot}. State-level clusters, not exact event positions. Inspection fallback uses reporting jurisdiction only. Alaska, Hawaii and Puerto Rico are insets.</p>
    {!print&&<div className="t3-coverage-controls"><label><input type="checkbox" checked={inspections} onChange={event=>setInspections(event.target.checked)}/> Inspections</label><label><input type="checkbox" checked={crashes} onChange={event=>setCrashes(event.target.checked)}/> Crashes</label><label>Inspect state <select value={selected??''} onChange={event=>setSelected(event.target.value||null)}><option value="">Select a state</option>{states.filter(state=>state.events.length).map(state=><option key={state.code}>{state.code}</option>)}</select></label></div>}
    <svg viewBox="0 0 760 560" aria-label="State clusters of loaded daily events" role="img"><title>State-level daily event clusters; symbol positions are not event coordinates</title>{states.map(state=><g key={state.code}><path d={state.path} fill={state.events.length?'#d5e7f2':'#f2f5f8'} stroke="#8496aa" strokeWidth="0.6"/>{state.events.length>0&&<g role="button" tabIndex={print?-1:0} aria-label={`${state.code}: ${state.events.length} events`} onClick={()=>setSelected(state.code)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(state.code);}}} className="t3-map-marker" transform={`translate(${state.x},${state.y})`}><title>{state.code}: {state.events.length} loaded events, grouped by state</title>{state.events.some(event=>event.kind==='inspection')&&<circle cx={-9} cy={0} r={8} fill="#125e89"/>}{state.events.some(event=>event.kind==='crash')&&<path d="M8,-9L17,7L-1,7Z" fill="#cf591d"/>}<text y={23} textAnchor="middle" fontSize={10} fill="#102c48">{state.code} {state.events.length}</text></g>}</g>)}</svg>
    <p className="t3-map-legend">● Blue circle: inspections · ▲ Orange triangle: crash involvement · numbers: loaded state totals. {geo.unlocated} rows have no mappable state; {geo.rejected} unrelated rows rejected. {result.sources.some(source=>source.error||source.slice?.truncated)?'Partial/unavailable sources: displayed counts are lower bounds.':'Complete for the selected source requests.'}</p>
    {!print&&selected&&<div className="t3-map-events"><h4>{selected}: {selectedEvents.length} loaded events</h4><p>First 50 shown. Select another state or toggle a layer to inspect other events.</p>{selectedEvents.slice(0,50).map(event=><p key={event.key}><strong>{event.kind} · {event.date}</strong> · {event.precision} · report {event.report} · location text: {event.location} · {event.source} {event.kind==='inspection'&&event.id&&<a href={`#/carrier/${event.dot}/inspection/${event.id}`}>Open inspection {event.id}</a>}</p>)}</div>}
    <small>Boundaries: U.S. Census Bureau, 2025, 1:20,000,000. No third-party geocoding or map-tile requests. Location text is retained as reported.</small>
    {!print&&<div className="c360-split">{result.sources.map(source=>source.slice&&!source.error?<Bars key={source.id} title={source.label} rows={windowMonths(source.slice).map(month=>({label:month.month,count:month.loaded}))} note={source.slice.truncated?'Loaded lower bounds, including zero-loaded months.':'Returned rows in the selected inclusive window.'}/>:<p key={source.id}>{source.label}: unavailable.</p>)}</div>}
  </section>;
}
